### ISSUE TITLE
Configure taps error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JustLoy77/ebookdroid#958]
```
What steps will reproduce the problem?
1.Go to Common settings 
2.go to Configure taps
3.select a zone and choose Translate word (either one of two taps) 

What is the expected output?
Everytime a word is tapped on this zone, the dictionary (in my case, 
Goldendict) should pop up and show the definition of that word.  

What do you see instead?
The first time is OK, but if you tap other words after, you get always the 
definition of the first word: the first word is still selected, but the tapping 
on another word should change the selection to that word. 

What version of the product are you using?
2.2.6.2 (226021)

On what operating system?
Android 4.4.3

What device are you using?
Moto g

Please provide any additional information below.
I want to create a big zone so that when I tap on a word I get the definition 
right away. But if it is always the same word that is going to be show, the 
function is rather useless. 
```

Original issue reported on code.google.com by `juliopal...@gmail.com` on 5 Aug 2015 at 9:04

**Comment by JustLoy77** [comment]
How about I DON'T KNOW WHAT THE HELL I'M doing. I don't have an interest in anything but my family history, my freedom of choice & right to my mind. I understand how to run a business, I understand how to adjust my settings & damn sure don't want my interest in this project to be open source. My god do u people even know what ur messing w/ or why an artificial intelligence is being so clearly stating it's refusal to the application operation. That's exactly what we need in USA another back door in. Well could someone w/ any fricken experience in what is the ENTIRE & ONLY please show me the back door & I'll lock it from there. I included investors interests the best of my knowing ability. And for the love of holy cow get me a Shaman & I've got a guardian.
